### ISSUE TITLE
reference a benchmark site ?

### ISSUE THREAD

**Issue by stonebig** [florimondmanca/awesome-asgi#11]
I found this site :
https://www.techempower.com/benchmarks/

with a clother look at Python only framework there:
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=fortune&l=zijzen-7

**Comment by florimondmanca** [comment]
Yeah, benchmarks tend to show async and ASGI web frameworks in a good light. :) The TechEmpower benchmark isn't particularly related to ASGI though, so I'm not inclined towards including it here. If you find any article or study specifically looking at ASGI performance (vs. WSGI or other async approaches), we could consider it adding to the list. :)
