### ISSUE TITLE
Usage-centric classification

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/awesome-asgi#25]
Discussion in https://github.com/florimondmanca/awesome-asgi/pull/24#discussion_r362583829 brought up to me that the categories in this list may not be optimal right now.

Eg. we have "applications", "libraries", and "middleware", and the separation between the three may not be clear enough.

If this list is aimed at promoting projects that help work with ASGI (i.e. mainly building web apps), then perhaps we could switch to a more use-case-centric classification, where each section is an answer to "how do I XYZ with ASGI?".

(We have this for "application frameworks" vs "servers", which respectively address "how do I build an ASGI web app" and "how do I serve it on the internet", and I think it works well.)

**Comment by adamchainz** [comment]
You could steal the categories from awesome-django? :)

**Comment by erm** [comment]
I think this is a pretty good approach and makes it a bit easier to navigate - good idea. 

I'm not sure how much further to divide the sections, but perhaps there should be sub-categories as well? For example, I was thinking a better name for "Meta" might be "Resources", then under that section could be Tutorials, Publications, ASGI reference, etc. I took a look at https://github.com/wsvincent/awesome-django#resources and it seems like a nice way of doing it.

**Comment by florimondmanca** [comment]
@adamchainz @erm I pushed a version of #27 that takes *some* inspiration from how awesome-django does things. Would love to hear your thoughts there!

**Comment by adamchainz** [comment]
👍
