### ISSUE TITLE
An ASGI toy example

### ISSUE THREAD

**Issue by qweeze** [florimondmanca/awesome-asgi#53]
Hi!
I wrote a very tiny [ASGI web framework](https://github.com/qweeze/nanoasgi) as an experiment and I thought maybe I could share it here. It is not for production usage of course but it could be useful as a learning resource to grasp the concept of how does ASGI work and to demystify how asyncio frameworks operate under the hood on a toy example. I'm not sure if it fits in this list so if it doesn't - please close this :)

**Comment by florimondmanca** [comment]
Hello!

The code there is really nice and lovely. Great one! :)

I _guess_ we could consider several things:

* Expand the "Application frameworks",optionally list this in a "Toy examples" sub-list.
* Add a new "Toy examples" section (perhaps under "Resources", but not sure). I can think of other little projects and gists that could fit there — eg an HTTPCore-backed proxy service running on ASGI Tom Christie wrote a while back.

I think I'd prefer the second option, with a new separate "Toy projects and examples" section. WDYT?

**Comment by qweeze** [comment]
Thanks! 

> new separate "Toy projects and examples" section

I like this option too, seems a bit more suitable place for such projects to me. Submitted a PR here - #54
