### ISSUE TITLE
add a release when README gets updated

### ISSUE THREAD

**Issue by mrezzamoradi** [florimondmanca/awesome-asgi#7]
Thanks for maintaining this awesome list. I'd like to suggest to add a release when a change is made to the README file. With this, we can watch the project without getting lots of activity emails.

**Comment by florimondmanca** [comment]
Ah, interesting idea. Do you have an example of another awesome list project doing this? I'm mainly wondering which scheme to use to tag releases. Right now I'm thinking of using [Calver](https://calver.org), e.g. `2019.08.11`.

**Comment by florimondmanca** [comment]
Adopted — I will now publish releases using Calver when the list changes. First release has just been made. Thanks for suggesting this idea. :-)

**Comment by mrezzamoradi** [comment]
Nice job :+1:  
There is a little typo in release tag ;)

**Comment by florimondmanca** [comment]
> There is a little typo in release tag ;)

Ah, for some reason I'm not seeing it — where is the typo exactly?

**Comment by mrezzamoradi** [comment]
> > There is a little typo in release tag ;)
> 
> Ah, for some reason I'm not seeing it — where is the typo exactly?
It has to be `2018.08.11` but it is `2018.08.1`

**Comment by florimondmanca** [comment]
> It has to be 2018.08.11 but it is 2018.08.1

Hmm… So in the current `YYYY.0M.MICRO` scheme it actually should have been `2019.08.0` (micro starts at 0). But I think the problem is that this scheme is confusing. The reason for not including the day is because there *might* be multiple releases a day. I think I'll switch to `YY.M.MICRO` instead, e.g. `19.8.0`. :-)
