### ISSUE TITLE
ASGI middlewares

### ISSUE THREAD

**Issue by adriangb** [florimondmanca/awesome-asgi#85]
I have a couple experimental ASGI middlewares that are interesting at least from an academic standpoint/understanding how ASGI works. Should I make a PR to add them? Under what section?

- https://github.com/adriangb/asgi-routing (you folks might find https://github.com/adriangb/asgi-routing/blob/main/asgi_routing/_lifespan_dispatcher.py particularly amusing)
- https://github.com/adriangb/asgi-background
- https://github.com/adriangb/asgi-lifespan

**Comment by florimondmanca** [comment]
@adriangb Hey, coming back to this. Would you be comfortable adding these to « Toy projects and examples »? We might want to rename that section to « Experiments and examples », for everything in the « trying (new) things out » area?

**Comment by adriangb** [comment]
Yep, that sounds great to me! `Experiments and examples` also sounds better than "toy"
