### ISSUE TITLE
Intro to ASGI spec PyconUS 2023 talk

### ISSUE THREAD

**Issue by florimondmanca** [florimondmanca/awesome-asgi#86]
Let’s consider adding @adriangb’d talk at PyConUS 2023 to this list once the replay’s out :)

« Inside your web framework: intro to the ASGI spec, middleware and apps »

https://twitter.com/pauloxnet/status/1649824653341499392

https://us.pycon.org/2023/schedule/presentation/5/

**Comment by Kludex** [comment]
@adriangb :P

**Comment by florimondmanca** [comment]
It’s out

https://m’youtube.com/watch?v=fcfyDvK_A6Q

But it seems there’s a sound issue — we can only here blips here and there, and nothing or Adrian’s talking. Perhaps it’s going to be fixed soon.

**Comment by adriangb** [comment]
It sounds okay to me, maybe they've fixed it?

**Comment by florimondmanca** [comment]
Apparently the sound is off on mono speakers, eg phone speaker, due to some recording issue. Will need to try on the stereo laptop or headphones.

Anyway, still need to watch the talk, but I think we can already add it as a strong candidate!
