### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by Archmonger** [florimondmanca/awesome-asgi#95]
Last commit was 8 months ago. Was considering PRing to add [`ReactPy`](https://github.com/reactive-python/reactpy), [`granian`](https://github.com/emmett-framework/granian), and [`ServeStatic`](https://github.com/Archmonger/ServeStatic), but it seems like this repo hasn't had much activity lately.

**Comment by Kludex** [comment]
@florimondmanca If you want, I can help here.

**Comment by Archmonger** [comment]
+1 vote to adding Kludex as a maintainer, if additional help is needed.

**Comment by florimondmanca** [comment]
@Kludex Thanks for volunteering :pray: 

I added you as a collaborator and it seems until you accept I can't set a maintainer role yet, but I'm very happy to.

**Comment by Kludex** [comment]
Done. Thanks Florimond. :)

**Comment by florimondmanca** [comment]
Hmm I'm confused because I don't have any more options in the "Collaborators" section. Have you gained write access?

**Comment by Kludex** [comment]
> Hmm I'm confused because I don't have any more options in the "Collaborators" section. Have you gained write access?

Repos on the user's namespace work different than organization. On the organization, you have more granularity. I already have all the rights needed here (I can't change the repo settings - which is fine).

**Comment by Kludex** [comment]
We are good here. I'll help to maintain it. 👍 

Ping me if I don't see something.
