### ISSUE TITLE
Mangum is no longer maintained

### ISSUE THREAD

**Issue by andrewthetechie** [florimondmanca/awesome-asgi#96]
Mangum has been archived and is no longer maintained. It might be good to remove it from the list

**Comment by Kludex** [comment]
Was it replaced for something else?

**Comment by andrewthetechie** [comment]
I don't know of another good option

**Comment by Kludex** [comment]
Mangum is under my handler now. All good. 👍 

I'll keep maintaining the package.

**Comment by andrewthetechie** [comment]
@kludex could you give me some more details? What is your handler?

**Comment by Kludex** [comment]
I mean, the project was transferred to me.

**Comment by andrewthetechie** [comment]
Oh, very cool. Thanks for taking on maintaining it. Its got a backlog of issues :)
